// ---------- Extrude / face push-pull ----------
function profileShape(meta){const pts=meta.params.points||profilePointsFromParams(meta.params);if(!pts?.length)return null;const s=new THREE.Shape();s.moveTo(pts[0][0],pts[0][1]);pts.slice(1).forEach(p=>s.lineTo(p[0],p[1]));s.closePath();return s;}
function extrudeProfileObject(profile,distance,{bevel=0,segments=1,taper=0}={}){
  const meta=rs(profile),shape=profileShape(meta);if(!shape)return null;const depth=Math.abs(distance);let g;
  if(Math.abs(taper)>EPS)g=makeTaperedPrism(meta.params.points,depth,taper,meta.params.plane||'XY',Math.sign(distance)||1);
  else {g=new THREE.ExtrudeGeometry(shape,{depth,steps:1,bevelEnabled:bevel>0,bevelThickness:Math.min(bevel,depth*.45),bevelSize:bevel,bevelSegments:Math.max(1,segments),curveSegments:48});mapGeometryPlane(g,meta.params.plane||'XY',Math.sign(distance)||1);}
  const mesh=new THREE.Mesh(g,defaultMaterial());mesh.position.copy(profile.position);mesh.rotation.copy(profile.rotation);mesh.scale.copy(profile.scale);mesh.castShadow=mesh.receiveShadow=true;itemMeta(mesh,'solid',{feature:'extrude',distance,bevel,segments,taper,sourceProfile:meta.params});mesh.name=`Extrude ${app.objectCounter++}`;return mesh;
}
function makeTaperedPrism(points,depth,taperDeg,plane,sign=1){const n=points.length,verts=[],idx=[],factor=1-Math.tan(taperDeg*RAD)*depth/Math.max(1,Math.max(...points.map(p=>Math.hypot(...p))));const f=Math.max(.05,factor);for(const z of [0,depth*sign])for(const p of points){const s=z===0?1:f;const w=uvWorld([p[0]*s,p[1]*s],plane,Math.abs(z));if(sign<0){const norm=plane==='XY'?new THREE.Vector3(0,0,-1):plane==='XZ'?new THREE.Vector3(0,-1,0):new THREE.Vector3(-1,0,0);w.copy(uvWorld([p[0]*s,p[1]*s],plane,0)).addScaledVector(norm,Math.abs(z));}verts.push(w.x,w.y,w.z);}for(let i=0;i<n;i++){const j=(i+1)%n;idx.push(i,j,n+j,i,n+j,n+i);}for(let i=1;i<n-1;i++){idx.push(0,i+1,i);idx.push(n,n+i,n+i+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g;}
async function doExtrude({pushPull=false}={}){
  if(rs(app.selected)?.kind==='profile'){
    openOperation(pushPull?'Push / Pull':'Extrude',[
      {key:'distance',label:'Distance (mm)',type:'number',value:25,step:.1},
      {key:'taper',label:'Taper / draft angle (°)',type:'number',value:0,step:.1},
      {key:'operation',label:'Operation',type:'select',value:'new',options:[['new','New body'],['join','Join checked body'],['cut','Cut checked body'],['intersect','Intersect checked body']]}
    ],async v=>{const before=captureState();const mesh=extrudeProfileObject(app.selected,safeNum(v.distance,25),{taper:safeNum(v.taper,0)});if(!mesh)return;let final=mesh;if(v.operation!=='new'){const target=app.checked.find(x=>x!==app.selected&&x.isMesh);if(!target){return setStatus('Check one target solid for Join/Cut/Intersect.');}final=await booleanObjects(target,mesh,v.operation==='join'?'union':v.operation);modelRoot.remove(target);}
      modelRoot.add(final);app.selected.visible=false;selectObject(final);addFeature(final,pushPull?'Push/Pull':'Extrude');pushHistory(pushPull?'Push/Pull':'Extrude',before);fitObjects([final]);});return;
  }
  if(pushPull&&app.selected?.isMesh&&app.lastHit?.root===app.selected){return pushPullFace(app.selected,app.lastHit);}
  setStatus(pushPull?'Select a profile or click a planar face first.':'Select a closed sketch profile first.');
}
async function pushPullFace(obj,hit){
  const face=extractPlanarFace(obj,hit);if(!face)return setStatus('This face could not be isolated. Push/Pull currently requires a planar face.');
  openOperation('Push / Pull Face',[{key:'distance',label:'Distance (mm; negative cuts inward)',type:'number',value:10,step:.1}],async v=>{const d=safeNum(v.distance,10);if(Math.abs(d)<EPS)return;const before=captureState(),prism=extrudeWorldPolygon(face.points,face.normal,d);if(!prism)return;const result=await booleanObjects(obj,prism,d>=0?'union':'cut');modelRoot.remove(obj);selectObject(result);addFeature(result,`Face Push/Pull ${round(d)} mm`);pushHistory('Face Push/Pull',before);});
}
function extractPlanarFace(obj,hit){
  const g=obj.geometry;if(!g?.attributes?.position||!hit.face)return null;const normal=hit.face.normal.clone().transformDirection(obj.matrixWorld).normalize(),origin=hit.point.clone();const pos=g.attributes.position,index=g.index;const pts=[];const triCount=index?index.count/3:pos.count/3;const nm=new THREE.Matrix3().getNormalMatrix(obj.matrixWorld);
  for(let t=0;t<triCount;t++){const ids=index?[index.getX(t*3),index.getX(t*3+1),index.getX(t*3+2)]:[t*3,t*3+1,t*3+2];const vs=ids.map(i=>new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(obj.matrixWorld));const n=vs[1].clone().sub(vs[0]).cross(vs[2].clone().sub(vs[0])).normalize();if(Math.abs(n.dot(normal))>.999&&Math.abs(vs[0].clone().sub(origin).dot(normal))<1e-3)pts.push(...vs);}
  const unique=[];pts.forEach(p=>{if(!unique.some(q=>q.distanceToSquared(p)<1e-8))unique.push(p)});if(unique.length<3)return null;const u=Math.abs(normal.z)<.9?new THREE.Vector3(0,0,1).cross(normal).normalize():new THREE.Vector3(1,0,0).cross(normal).normalize(),v=normal.clone().cross(u).normalize();const p2=unique.map(p=>[p.clone().sub(origin).dot(u),p.clone().sub(origin).dot(v),p]);const hull=convexHull(p2.map(x=>[x[0],x[1]]));const world=hull.map(h=>origin.clone().addScaledVector(u,h[0]).addScaledVector(v,h[1]));return {points:world,normal,origin,u,v};
}
function convexHull(points){if(points.length<=3)return points;const p=[...points].sort((a,b)=>a[0]-b[0]||a[1]-b[1]),cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]);const lo=[];for(const x of p){while(lo.length>=2&&cross(lo.at(-2),lo.at(-1),x)<=0)lo.pop();lo.push(x)}const hi=[];for(let i=p.length-1;i>=0;i--){const x=p[i];while(hi.length>=2&&cross(hi.at(-2),hi.at(-1),x)<=0)hi.pop();hi.push(x)}lo.pop();hi.pop();return lo.concat(hi);}
function extrudeWorldPolygon(points,normal,d){const origin=points[0],u=points[1].clone().sub(origin).normalize(),v=normal.clone().cross(u).normalize(),shape=new THREE.Shape();const xy=points.map(p=>[p.clone().sub(origin).dot(u),p.clone().sub(origin).dot(v)]);shape.moveTo(xy[0][0],xy[0][1]);xy.slice(1).forEach(p=>shape.lineTo(p[0],p[1]));shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth:Math.abs(d),bevelEnabled:false});const a=g.attributes.position.array;for(let i=0;i<a.length;i+=3){const q=origin.clone().addScaledVector(u,a[i]).addScaledVector(v,a[i+1]).addScaledVector(normal,a[i+2]*(Math.sign(d)||1));a[i]=q.x;a[i+1]=q.y;a[i+2]=q.z;}g.attributes.position.needsUpdate=true;g.computeVertexNormals();return new THREE.Mesh(g,defaultMaterial());}
