// ---------- Organization ----------
function groupChecked(){const arr=app.checked.length?app.checked:(app.selected?[app.selected]:[]);if(arr.length<1)return;const before=captureState(),group=new THREE.Group();itemMeta(group,'group',{});group.name=`Group ${app.objectCounter++}`;modelRoot.add(group);arr.forEach(o=>{o.updateMatrixWorld(true);const world=o.matrixWorld.clone();group.attach(o);o.matrix.copy(group.matrixWorld.clone().invert().multiply(world));o.matrix.decompose(o.position,o.quaternion,o.scale);});app.checked=[];selectObject(group);addFeature(group,'Group');pushHistory('Group',before);renderSceneList();}
function ungroupSelected(){const g=app.selected;if(!g?.isGroup||g===modelRoot)return setStatus('Select a group to ungroup.');const before=captureState(),children=[...g.children];children.forEach(c=>modelRoot.attach(c));modelRoot.remove(g);selectObject(children[0]||null);pushHistory('Ungroup',before);renderSceneList();}
function makeComponent(){const o=app.selected;if(!o)return;const before=captureState(),id=rs(o)?.componentId||uid();rs(o).componentId=id;rs(o).kind='component';addFeature(o,'Make Component');pushHistory('Make Component',before);renderSceneList();setStatus('Component created. New instances share the same component ID.');}
function newComponentInstance(){const o=app.selected,m=rs(o);if(!o||!m?.componentId)return setStatus('Select a component first.');const before=captureState(),c=o.clone(true);c.traverse(x=>{if(x.isMesh){x.geometry=x.geometry; x.material=x.material;}});c.userData=JSON.parse(JSON.stringify(o.userData));rs(c).id=uid();c.position.x+=20;c.name=`${o.name} Instance`;modelRoot.add(c);selectObject(c);pushHistory('Component Instance',before);renderSceneList();}
function toggleLock(){if(!app.selected)return;const before=captureState();rs(app.selected).locked=!rs(app.selected).locked;if(rs(app.selected).locked)transform.detach();else transform.attach(app.selected);pushHistory('Lock / Unlock',before);renderSceneList();}
function toggleHide(){if(!app.selected)return;const before=captureState();app.selected.visible=!app.selected.visible;pushHistory('Hide / Show',before);renderSceneList();}
function refreshTagSelect(){const sel=$('objectTag'),current=sel.value;sel.innerHTML='';app.tags.forEach(t=>sel.add(new Option(t.name,t.id)));if([...sel.options].some(o=>o.value===current))sel.value=current;}
function renderTags(){const root=$('tagList');root.innerHTML='';app.tags.forEach(t=>{const row=document.createElement('div');row.className='mini-row';const ck=document.createElement('input');ck.type='checkbox';ck.checked=t.visible;ck.addEventListener('change',()=>{t.visible=ck.checked;allItems().filter(o=>(rs(o)?.tag||'untagged')===t.id).forEach(o=>o.visible=t.visible);renderSceneList();});const name=document.createElement('span');name.textContent=t.name;row.append(ck,name);root.append(row);});refreshTagSelect();}
function addTag(){const name=$('newTagName').value.trim();if(!name)return;if(app.tags.some(t=>t.name.toLowerCase()===name.toLowerCase()))return setStatus('That tag already exists.');app.tags.push({id:uid(),name,visible:true});$('newTagName').value='';renderTags();pushHistory('Add Tag');}
function renderScenes(){const root=$('sceneViewList');root.innerHTML='';app.scenes.forEach((s,i)=>{const row=document.createElement('div');row.className='mini-row';const btn=document.createElement('button');btn.className='tiny';btn.textContent='Go';btn.addEventListener('click',()=>restoreSceneView(i));const name=document.createElement('span');name.textContent=s.name;const del=document.createElement('button');del.className='tiny';del.textContent='×';del.addEventListener('click',()=>{app.scenes.splice(i,1);renderScenes();});row.append(btn,name,del);root.append(row);});}
function addSceneView(){const name=$('newSceneName').value.trim()||`Scene ${app.scenes.length+1}`;const visibility=Object.fromEntries(allItems().map(o=>[rs(o).id,o.visible]));app.scenes.push({name,camera:{position:camera.position.toArray(),target:orbit.target.toArray(),zoom:camera.zoom,projection:camera===orthoCamera?'orthographic':'perspective'},visibility,display:$('displayMode').value});$('newSceneName').value='';renderScenes();pushHistory('Add Scene');}
function restoreSceneView(i){const s=app.scenes[i];if(!s)return;if((s.camera.projection==='orthographic')!==(camera===orthoCamera))toggleProjection();camera.position.fromArray(s.camera.position);orbit.target.fromArray(s.camera.target);camera.zoom=s.camera.zoom||1;camera.updateProjectionMatrix();allItems().forEach(o=>{if(s.visibility[rs(o).id]!=null)o.visible=s.visibility[rs(o).id]});$('displayMode').value=s.display||'shaded';applyDisplayMode();orbit.update();renderSceneList();}

// ---------- Render / materials ----------
function applyDisplayMode(){const mode=$('displayMode').value;materialMeshes(modelRoot).forEach(m=>{const mat=m.material;if(!mat)return;if(mode==='wireframe'){mat.wireframe=true;mat.transparent=false;mat.opacity=1;}else{mat.wireframe=false;if(mode==='xray'){mat.transparent=true;mat.opacity=.28;mat.depthWrite=false;}else{mat.transparent=false;mat.opacity=1;mat.depthWrite=true;}if(mode==='monochrome')mat.color.set(0xd7dbe2);else if(m.userData.originalColor)mat.color.set(m.userData.originalColor);else m.userData.originalColor=`#${mat.color.getHexString()}`;}m.material.needsUpdate=true;});allItems().forEach(o=>toggleEdgeOverlay(o,mode==='edges'));}
function toggleEdgeOverlay(obj,on){if(!obj)return;const old=obj.getObjectByName?.('__edges');if(old&&!on){obj.remove(old);old.geometry.dispose();old.material.dispose();}if(on&&!old&&obj.isMesh){const e=new THREE.LineSegments(new THREE.EdgesGeometry(obj.geometry,25),new THREE.LineBasicMaterial({color:0x182033}));e.name='__edges';e.userData.helper=true;obj.add(e);}}
function addLight(kind){const before=captureState();if(kind==='point'){const l=new THREE.PointLight(0xffffff,3,500);l.position.set(80,-80,120);l.name='Point Light';lightRoot.add(l);}else{const l=new THREE.SpotLight(0xffffff,4,600,Math.PI/5,.4);l.position.set(100,-100,160);l.target.position.set(0,0,0);lightRoot.add(l,l.target);}pushHistory(`Add ${kind} light`,before);setStatus(`${capitalize(kind)} light added.`);}

// ---------- Project import/export ----------
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function saveProject(){const blob=new Blob([JSON.stringify(serializeProjectObject())],{type:'application/json'});downloadBlob(blob,`render-studio-${new Date().toISOString().slice(0,10)}.json`);setStatus('Project saved.');}
async function openProjectFile(file){try{await restoreState(await file.text());app.history=[];app.historyIndex=-1;pushHistory('Open Project');setStatus('Project loaded.');}catch(e){console.error(e);setStatus('Could not open this project file.');}}
function newProject(){if(allItems().length&&!confirm('Start a new project? Unsaved model changes will be cleared.'))return;const before=captureState();modelRoot.clear();guideRoot.clear();constructionRoot.clear();app.tags=[{id:'untagged',name:'Untagged',visible:true}];app.scenes=[];app.checked=[];selectObject(null);renderTags();renderScenes();renderSceneList();pushHistory('New Project',before);setStatus('New project.');}
function importSTL(file){const reader=new FileReader();reader.onload=()=>{try{const before=captureState(),g=new STLLoader().parse(reader.result);g.computeVertexNormals();const m=new THREE.Mesh(g,defaultMaterial());addItem(m,'import',{format:'STL'},file.name.replace(/\.stl$/i,''));placeOnGround(m,false);pushHistory('Import STL',before);fitObjects([m]);setStatus(`Imported ${file.name}.`);}catch(e){console.error(e);setStatus('Could not import STL.');}};reader.readAsArrayBuffer(file);}
function exportScene(type='stl'){const target=app.selected||modelRoot;if(type==='stl'){const out=new STLExporter().parse(target,{binary:true});downloadBlob(new Blob([out],{type:'model/stl'}),'render-studio.stl');}else{const txt=new OBJExporter().parse(target);downloadBlob(new Blob([txt],{type:'text/plain'}),'render-studio.obj');}}
