// ---------- CSG ----------
async function loadCSG(){if(app.csg)return app.csg;setStatus('Loading solid-operation engine…');app.csg=await import('https://esm.sh/three-bvh-csg@0.0.18?external=three');return app.csg;}
async function booleanObjects(a,b,mode){const mod=await loadCSG(),{Brush,Evaluator,ADDITION,SUBTRACTION,INTERSECTION}=mod,evaluator=new Evaluator();evaluator.useGroups=false;const brushA=worldBrush(a,Brush),brushB=worldBrush(b,Brush);const op=mode==='union'?ADDITION:mode==='cut'?SUBTRACTION:INTERSECTION;const r=evaluator.evaluate(brushA,brushB,op);r.geometry=stripDrawRange(r.geometry);r.geometry.computeVertexNormals();r.material=cloneMaterial(firstMesh(a)?.material)||defaultMaterial();r.castShadow=r.receiveShadow=true;itemMeta(r,'solid',{feature:`boolean-${mode}`});r.name=`${capitalize(mode)} ${app.objectCounter++}`;modelRoot.add(r);return r;}
function worldBrush(obj,Brush){obj.updateMatrixWorld(true);let mesh=firstMesh(obj)||obj;const g=mesh.geometry.clone();g.applyMatrix4(mesh.matrixWorld);if(g.groups?.length)g.clearGroups();const br=new Brush(g,cloneMaterial(mesh.material)||defaultMaterial());br.updateMatrixWorld(true);return br;}
function stripDrawRange(g){const clone=g.clone();clone.setDrawRange(0,Infinity);return clone;}
function cloneMaterial(m){if(Array.isArray(m))return m[0]?.clone();return m?.clone?.();}
async function doBoolean(mode){const arr=app.checked.filter(x=>x.isMesh||firstMesh(x));if(arr.length!==2)return setStatus('Check exactly two solid objects.');const before=captureState(),r=await booleanObjects(arr[0],arr[1],mode);modelRoot.remove(arr[0],arr[1]);app.checked=[];selectObject(r);addFeature(r,`Boolean ${mode}`);pushHistory(`Boolean ${mode}`,before);fitObjects([r]);}

// ---------- Patterns / align / mirror ----------
function cloneModelObject(o){const c=o.clone(true);c.traverse(x=>{if(x.isMesh){x.geometry=x.geometry.clone();x.material=cloneMaterial(x.material)||defaultMaterial();}});c.userData=JSON.parse(JSON.stringify(o.userData||{}));if(rs(c))rs(c).id=uid();c.name=`${o.name} Copy`;return c;}
function rectangularPattern(){const o=app.selected;if(!o)return setStatus('Select an object to pattern.');openOperation('Rectangular Pattern',[{key:'countX',label:'X count',type:'number',value:3,step:1},{key:'spacingX',label:'X spacing (mm)',type:'number',value:30,step:.1},{key:'countY',label:'Y count',type:'number',value:1,step:1},{key:'spacingY',label:'Y spacing (mm)',type:'number',value:30,step:.1}],v=>{const before=captureState(),cx=clamp(Math.round(v.countX),1,100),cy=clamp(Math.round(v.countY),1,100);for(let x=0;x<cx;x++)for(let y=0;y<cy;y++){if(x===0&&y===0)continue;const c=cloneModelObject(o);c.position.x+=x*safeNum(v.spacingX,30);c.position.y+=y*safeNum(v.spacingY,30);modelRoot.add(c);}addFeature(o,`Rectangular pattern ${cx}×${cy}`);pushHistory('Rectangular Pattern',before);renderSceneList();});}
function circularPattern(){const o=app.selected;if(!o)return setStatus('Select an object to pattern.');openOperation('Circular Pattern',[{key:'count',label:'Count',type:'number',value:6,step:1},{key:'angle',label:'Total angle (°)',type:'number',value:360,step:1},{key:'axis',label:'Axis',type:'select',value:'Z',options:[['Z','Z'],['X','X'],['Y','Y']]}],v=>{const before=captureState(),n=clamp(Math.round(v.count),2,100),angle=safeNum(v.angle,360)*RAD,axis=v.axis||'Z';for(let i=1;i<n;i++){const c=cloneModelObject(o),a=angle*i/n;if(axis==='Z'){const x=o.position.x,y=o.position.y;c.position.x=x*Math.cos(a)-y*Math.sin(a);c.position.y=x*Math.sin(a)+y*Math.cos(a);c.rotation.z+=a;}else if(axis==='Y'){const x=o.position.x,z=o.position.z;c.position.x=x*Math.cos(a)+z*Math.sin(a);c.position.z=-x*Math.sin(a)+z*Math.cos(a);c.rotation.y+=a;}else{const y=o.position.y,z=o.position.z;c.position.y=y*Math.cos(a)-z*Math.sin(a);c.position.z=y*Math.sin(a)+z*Math.cos(a);c.rotation.x+=a;}modelRoot.add(c);}addFeature(o,`Circular pattern ×${n}`);pushHistory('Circular Pattern',before);renderSceneList();});}
function pathPattern(){const o=app.selected,path=app.checked.find(x=>rs(x)?.kind==='path');if(!o||!path)return setStatus('Select an object and check a path.');openOperation('Pattern Along Path',[{key:'count',label:'Count',type:'number',value:5,step:1}],v=>{const before=captureState(),n=clamp(Math.round(v.count),2,100),pts=worldPathPoints(path),curve=new THREE.CatmullRomCurve3(pts);for(let i=1;i<n;i++){const c=cloneModelObject(o);c.position.copy(curve.getPointAt(i/(n-1)));modelRoot.add(c);}addFeature(o,`Path pattern ×${n}`);pushHistory('Pattern Along Path',before);renderSceneList();});}
function mirrorSelected(){const o=app.selected;if(!o)return;openOperation('Mirror',[{key:'axis',label:'Mirror across',type:'select',value:'X',options:[['X','YZ plane (flip X)'],['Y','XZ plane (flip Y)'],['Z','XY plane (flip Z)']]},{key:'copy',label:'Keep original',type:'checkbox',value:true}],v=>{const before=captureState(),c=v.copy?cloneModelObject(o):o;if(v.axis==='X'){c.scale.x*=-1;c.position.x*=-1;}else if(v.axis==='Y'){c.scale.y*=-1;c.position.y*=-1;}else{c.scale.z*=-1;c.position.z*=-1;}if(v.copy)modelRoot.add(c);selectObject(c);addFeature(c,`Mirror ${v.axis}`);pushHistory('Mirror',before);renderSceneList();});}
function alignChecked(){const arr=app.checked.length?app.checked:(app.selected?[app.selected]:[]);if(arr.length<2)return setStatus('Check at least two objects to Align.');openOperation('Align',[{key:'axis',label:'Axis',type:'select',value:'X',options:[['X','X'],['Y','Y'],['Z','Z']]},{key:'mode',label:'Alignment',type:'select',value:'center',options:[['min','Minimum'],['center','Center'],['max','Maximum']]}],v=>{const before=captureState(),ref=new THREE.Box3().setFromObject(arr[0]),get=(b)=>{if(v.axis==='X')return v.mode==='min'?b.min.x:v.mode==='max'?b.max.x:(b.min.x+b.max.x)/2;if(v.axis==='Y')return v.mode==='min'?b.min.y:v.mode==='max'?b.max.y:(b.min.y+b.max.y)/2;return v.mode==='min'?b.min.z:v.mode==='max'?b.max.z:(b.min.z+b.max.z)/2},target=get(ref);arr.slice(1).forEach(o=>{const b=new THREE.Box3().setFromObject(o),delta=target-get(b);o.position[v.axis.toLowerCase()]+=delta;});pushHistory('Align',before);syncInspector(false);});}

// ---------- Construction ----------
function addConstructionPlane(kind='offset'){
  const d=safeNum($('constructionDistance').value,10),ang=safeNum($('constructionAngle').value,45)*RAD,geo=new THREE.PlaneGeometry(130,130),mat=new THREE.MeshBasicMaterial({color:0xf0c35a,transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false}),p=new THREE.Mesh(geo,mat);p.userData.helper=true;p.name=`${capitalize(kind)} Plane`;
  if(kind==='offset')p.position.z=d;else if(kind==='angle')p.rotation.x=ang;else p.position.z=d/2;
  constructionRoot.add(p);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(geo),lineMaterial(0xf0c35a));edges.userData.helper=true;p.add(edges);setStatus(`${p.name} created.`);pushHistory(`Create ${p.name}`);
}
function addConstructionAxis(){const pts=[new THREE.Vector3(0,0,-100),new THREE.Vector3(0,0,100)],l=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),lineMaterial(0xf0c35a));l.userData.helper=true;l.name='Construction Axis';constructionRoot.add(l);pushHistory('Construction Axis');setStatus('Construction axis created on Z.');}
function addConstructionPoint(){const g=new THREE.SphereGeometry(1.4,16,8),m=new THREE.MeshBasicMaterial({color:0xf0c35a}),p=new THREE.Mesh(g,m);p.userData.helper=true;p.name='Construction Point';if(app.lastHit?.point)p.position.copy(app.lastHit.point);constructionRoot.add(p);pushHistory('Construction Point');setStatus('Construction point created.');}
function clearGuides(){const before=captureState();guideRoot.clear();pushHistory('Clear Guides',before);setStatus('Guides cleared.');}
