// ---------- Inspect ----------
function meshProperties(mesh){
  const g=mesh.geometry;if(!g?.attributes?.position)return{area:0,volume:0,center:new THREE.Vector3()};mesh.updateMatrixWorld(true);const pos=g.attributes.position,index=g.index;let area=0,volume=0,center=new THREE.Vector3(),weight=0,triCount=index?index.count/3:pos.count/3;
  for(let i=0;i<triCount;i++){const ids=index?[index.getX(i*3),index.getX(i*3+1),index.getX(i*3+2)]:[i*3,i*3+1,i*3+2],a=new THREE.Vector3().fromBufferAttribute(pos,ids[0]).applyMatrix4(mesh.matrixWorld),b=new THREE.Vector3().fromBufferAttribute(pos,ids[1]).applyMatrix4(mesh.matrixWorld),c=new THREE.Vector3().fromBufferAttribute(pos,ids[2]).applyMatrix4(mesh.matrixWorld),cross=b.clone().sub(a).cross(c.clone().sub(a)),ar=cross.length()/2,v=a.dot(b.clone().cross(c))/6,tc=a.clone().add(b).add(c).multiplyScalar(1/3);area+=ar;volume+=v;center.addScaledVector(tc,Math.abs(v));weight+=Math.abs(v);}
  if(weight>EPS)center.multiplyScalar(1/weight);else new THREE.Box3().setFromObject(mesh).getCenter(center);return{area,volume,center};
}
function doMassProps(){const o=app.selected;if(!o?.isMesh)return setStatus('Select a mesh/solid first.');const p=meshProperties(o);$('inspectOutput').innerHTML=`Surface area: <strong>${round(p.area)} mm²</strong><br>Volume: <strong>${round(Math.abs(p.volume))} mm³</strong><br>Approx. center of mass: <strong>${round(p.center.x)}, ${round(p.center.y)}, ${round(p.center.z)}</strong>`;}
function meshCheck(mesh=app.selected){if(!mesh?.isMesh)return setStatus('Select a mesh to check.');const g=mesh.geometry,index=g.index,pos=g.attributes.position;let deg=0;const edges=new Map(),triCount=index?index.count/3:pos.count/3;const key=(a,b)=>a<b?`${a}:${b}`:`${b}:${a}`;for(let i=0;i<triCount;i++){const ids=index?[index.getX(i*3),index.getX(i*3+1),index.getX(i*3+2)]:[i*3,i*3+1,i*3+2],a=new THREE.Vector3().fromBufferAttribute(pos,ids[0]),b=new THREE.Vector3().fromBufferAttribute(pos,ids[1]),c=new THREE.Vector3().fromBufferAttribute(pos,ids[2]);if(b.clone().sub(a).cross(c.clone().sub(a)).lengthSq()<1e-12)deg++;for(const [x,y] of [[ids[0],ids[1]],[ids[1],ids[2]],[ids[2],ids[0]]])edges.set(key(x,y),(edges.get(key(x,y))||0)+1);}const boundary=[...edges.values()].filter(n=>n===1).length,nonman=[...edges.values()].filter(n=>n>2).length;$('inspectOutput').innerHTML=`Triangles: <strong>${triCount}</strong><br>Degenerate: <strong>${deg}</strong><br>Boundary edges: <strong>${boundary}</strong><br>Non-manifold edge uses: <strong>${nonman}</strong><br>${boundary===0&&nonman===0?'Likely closed/watertight.':'Mesh may need repair.'}`;return{deg,boundary,nonman};}
function repairMesh(){const o=app.selected;if(!o?.isMesh)return setStatus('Select a mesh to repair.');const before=captureState();let g=o.geometry.clone();g=mergeVertices(g,1e-4);g.computeVertexNormals();o.geometry.dispose();o.geometry=g;addFeature(o,'Mesh Repair: weld vertices + normals');pushHistory('Repair Mesh',before);meshCheck(o);setStatus('Basic repair complete: welded near-identical vertices and rebuilt normals.');}
async function interferenceCheck(){const arr=app.checked.filter(x=>x.isMesh);if(arr.length!==2)return setStatus('Check exactly two solid meshes for Interference.');const ba=new THREE.Box3().setFromObject(arr[0]),bb=new THREE.Box3().setFromObject(arr[1]);if(!ba.intersectsBox(bb)){$('inspectOutput').innerHTML='<strong>No bounding-box interference.</strong>';return;}try{const r=await booleanObjects(arr[0],arr[1],'intersect'),p=meshProperties(r);modelRoot.remove(r);$('inspectOutput').innerHTML=`Interference detected.<br>Approx. overlap volume: <strong>${round(Math.abs(p.volume))} mm³</strong>`;}catch{$('inspectOutput').innerHTML='Bounding boxes overlap. Exact CSG interference check could not complete.';}}
function toggleSectionPlane(){if(app.sectionPlane){app.sectionPlane=null;updateClipping();setStatus('Section plane disabled.');return;}openOperation('Section Plane',[{key:'axis',label:'Normal axis',type:'select',value:'Z',options:[['X','X'],['Y','Y'],['Z','Z']]},{key:'offset',label:'Plane coordinate (mm)',type:'number',value:0,step:.1},{key:'flip',label:'Flip direction',type:'checkbox',value:false}],v=>{const n=v.axis==='X'?new THREE.Vector3(1,0,0):v.axis==='Y'?new THREE.Vector3(0,1,0):new THREE.Vector3(0,0,1);if(v.flip)n.negate();app.sectionPlane=new THREE.Plane(n,-safeNum(v.offset,0));updateClipping();setStatus('Section plane active. Click Section Plane again to disable.');});}
