// ---------- Solid creation / modification ----------
function worldProfilePoints(profile){const m=rs(profile),pts=m?.params?.points||profilePointsFromParams(m?.params||{});if(!pts)return[];return pts.map(p=>uvWorld(p,m.params.plane||'XY').applyMatrix4(profile.matrixWorld));}
function worldPathPoints(path){const meta=rs(path);if(meta?.params?.points)return meta.params.points.map(p=>new THREE.Vector3().fromArray(p).applyMatrix4(path.matrixWorld));const pos=path.geometry?.attributes?.position;if(!pos)return[];const out=[];for(let i=0;i<pos.count;i++)out.push(new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(path.matrixWorld));return out;}
function doRevolve(){const o=app.selected,m=rs(o);if(m?.kind!=='profile')return setStatus('Select a closed sketch profile to Revolve.');openOperation('Revolve',[{key:'angle',label:'Angle (°)',type:'number',value:360,step:1},{key:'axis',label:'Axis',type:'select',value:'Z',options:[['Z','Z axis'],['X','X axis'],['Y','Y axis']]}],v=>{const before=captureState(),pts=m.params.points||[];if(pts.length<3)return;const g=makeRevolveGeometry(pts,safeNum(v.angle,360),v.axis||'Z');const mesh=new THREE.Mesh(g,defaultMaterial());addItem(mesh,'solid',{feature:'revolve',sourceProfile:m.params,angle:safeNum(v.angle,360),axis:v.axis},`Revolve ${app.objectCounter++}`);o.visible=false;addFeature(mesh,'Revolve');pushHistory('Revolve',before);fitObjects([mesh]);});}
function makeRevolveGeometry(points,angleDeg=360,axis='Z'){const seg=Math.max(3,Math.round(Math.abs(angleDeg)/360*96)),rings=seg+1,n=points.length,verts=[],idx=[];for(let i=0;i<rings;i++){const a=angleDeg*RAD*i/seg,c=Math.cos(a),s=Math.sin(a);for(const p of points){const r=p[0],z=p[1];let q;if(axis==='Z')q=[r*c,r*s,z];else if(axis==='Y')q=[r*c,z,r*s];else q=[z,r*c,r*s];verts.push(...q);}}for(let i=0;i<seg;i++)for(let j=0;j<n-1;j++){const a=i*n+j,b=a+1,c=(i+1)*n+j+1,d=(i+1)*n+j;idx.push(a,b,c,a,c,d);}if(Math.abs(angleDeg)>=359.999){for(let i=0;i<seg;i++){const j=(i+1)%seg;idx.push(i*n,j*n,(j)*n+n-1,i*n,(j)*n+n-1,i*n+n-1);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g;}

function doSweep(){const profile=app.selected&&rs(app.selected)?.kind==='profile'?app.selected:app.checked.find(x=>rs(x)?.kind==='profile'),path=app.checked.find(x=>rs(x)?.kind==='path')||(app.selected&&rs(app.selected)?.kind==='path'?app.selected:null);if(!profile||!path)return setStatus('Select a profile and check a path for Sweep / Follow Me.');openOperation('Sweep / Follow Me',[{key:'twist',label:'Twist over path (°)',type:'number',value:0,step:1},{key:'scaleEnd',label:'End scale',type:'number',value:1,step:.05}],v=>{const before=captureState(),g=makeSweepGeometry(rs(profile).params.points,worldPathPoints(path),safeNum(v.twist,0),safeNum(v.scaleEnd,1));const mesh=new THREE.Mesh(g,defaultMaterial());addItem(mesh,'solid',{feature:'sweep',profile:rs(profile).params,path:rs(path).params},`Sweep ${app.objectCounter++}`);profile.visible=false;addFeature(mesh,'Sweep / Follow Me');pushHistory('Sweep / Follow Me',before);fitObjects([mesh]);});}
function makeSweepGeometry(profile2D,pathPts,twistDeg=0,scaleEnd=1){if(profile2D.length<3||pathPts.length<2)return new THREE.BufferGeometry();let cu=0,cv=0;profile2D.forEach(q=>{cu+=q[0];cv+=q[1];});cu/=profile2D.length;cv/=profile2D.length;profile2D=profile2D.map(q=>[q[0]-cu,q[1]-cv]);const curve=new THREE.CatmullRomCurve3(pathPts,false,'centripetal');const steps=Math.max(8,Math.min(160,pathPts.length*12)),frames=curve.computeFrenetFrames(steps,false),n=profile2D.length,verts=[],idx=[];for(let i=0;i<=steps;i++){const p=curve.getPointAt(i/steps),normal=frames.normals[i],binormal=frames.binormals[i],tw=twistDeg*RAD*i/steps,cs=Math.cos(tw),sn=Math.sin(tw),scale=1+(scaleEnd-1)*i/steps;for(const q of profile2D){const x=(q[0]*cs-q[1]*sn)*scale,y=(q[0]*sn+q[1]*cs)*scale;const w=p.clone().addScaledVector(normal,x).addScaledVector(binormal,y);verts.push(w.x,w.y,w.z);}}for(let i=0;i<steps;i++)for(let j=0;j<n;j++){const k=(j+1)%n,a=i*n+j,b=i*n+k,c=(i+1)*n+k,d=(i+1)*n+j;idx.push(a,b,c,a,c,d);}for(let j=1;j<n-1;j++){idx.push(0,j+1,j);const b=steps*n;idx.push(b,b+j,b+j+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g;}

function doLoft(){const profiles=app.checked.filter(x=>rs(x)?.kind==='profile');if(profiles.length<2)return setStatus('Check at least two sketch profiles for Loft.');const before=captureState(),g=makeLoftGeometry(profiles);if(!g)return setStatus('Loft needs valid closed profiles.');const mesh=new THREE.Mesh(g,defaultMaterial());addItem(mesh,'solid',{feature:'loft',profiles:profiles.map(x=>rs(x).params)},`Loft ${app.objectCounter++}`);profiles.forEach(p=>p.visible=false);addFeature(mesh,'Loft');pushHistory('Loft',before);fitObjects([mesh]);}
function resampleLoop(points,n){const seg=[],lens=[],totalObj={v:0};for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length],l=a.distanceTo(b);seg.push([a,b,l]);totalObj.v+=l;lens.push(totalObj.v);}const out=[];for(let k=0;k<n;k++){const d=totalObj.v*k/n;let prev=0;for(let i=0;i<seg.length;i++){if(d<=lens[i]||i===seg.length-1){const [a,b,l]=seg[i],t=l?((d-prev)/l):0;out.push(a.clone().lerp(b,clamp(t,0,1)));break;}prev=lens[i];}}return out;}
function makeLoftGeometry(profiles){const n=64,rings=profiles.map(p=>resampleLoop(worldProfilePoints(p),n));if(rings.some(r=>r.length<n))return null;const verts=[],idx=[];rings.forEach(r=>r.forEach(p=>verts.push(p.x,p.y,p.z)));for(let k=0;k<rings.length-1;k++)for(let j=0;j<n;j++){const q=(j+1)%n,a=k*n+j,b=k*n+q,c=(k+1)*n+q,d=(k+1)*n+j;idx.push(a,b,c,a,c,d);}for(let j=1;j<n-1;j++){idx.push(0,j+1,j);const b=(rings.length-1)*n;idx.push(b,b+j,b+j+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();return g;}

function doRib(){const path=app.selected&&rs(app.selected)?.kind==='path'?app.selected:app.checked.find(x=>rs(x)?.kind==='path');if(!path)return setStatus('Select a sketch line/path for Rib / Web.');openOperation('Rib / Web',[{key:'thickness',label:'Thickness (mm)',type:'number',value:3,step:.1},{key:'depth',label:'Depth / height (mm)',type:'number',value:20,step:.1}],v=>{const before=captureState(),pts=worldPathPoints(path),profile=[[-safeNum(v.thickness,3)/2,0],[safeNum(v.thickness,3)/2,0],[safeNum(v.thickness,3)/2,safeNum(v.depth,20)],[-safeNum(v.thickness,3)/2,safeNum(v.depth,20)]],g=makeSweepGeometry(profile,pts,0,1),m=new THREE.Mesh(g,defaultMaterial());addItem(m,'solid',{feature:'rib',thickness:v.thickness,depth:v.depth},`Rib ${app.objectCounter++}`);addFeature(m,'Rib / Web');pushHistory('Rib / Web',before);});}

async function doHole(){const target=app.selected?.isMesh?app.selected:app.checked.find(x=>x.isMesh);if(!target)return setStatus('Select a solid body for Hole.');const b=new THREE.Box3().setFromObject(target),c=new THREE.Vector3();b.getCenter(c);openOperation('Hole',[{key:'diameter',label:'Diameter (mm)',type:'number',value:8,step:.1},{key:'depth',label:'Depth (mm; 0 = through)',type:'number',value:0,step:.1},{key:'axis',label:'Direction',type:'select',value:'Z',options:[['Z','Z'],['X','X'],['Y','Y']]},{key:'x',label:'Center X',type:'number',value:round(c.x),step:.1},{key:'y',label:'Center Y',type:'number',value:round(c.y),step:.1},{key:'z',label:'Center Z',type:'number',value:round(c.z),step:.1}],async v=>{const before=captureState(),size=new THREE.Vector3();b.getSize(size),axis=v.axis||'Z',depth=safeNum(v.depth,0)||Math.max(size.x,size.y,size.z)*2+20,r=safeNum(v.diameter,8)/2;let g=new THREE.CylinderGeometry(r,r,depth,64);g.rotateX(Math.PI/2);const tool=new THREE.Mesh(g,defaultMaterial());tool.position.set(safeNum(v.x,c.x),safeNum(v.y,c.y),safeNum(v.z,c.z));if(axis==='X')tool.rotation.y=Math.PI/2;else if(axis==='Y')tool.rotation.x=Math.PI/2;tool.updateMatrixWorld(true);const result=await booleanObjects(target,tool,'cut');modelRoot.remove(target);selectObject(result);addFeature(result,`Hole Ø${round(r*2)} mm`);pushHistory('Hole',before);});}

async function doThread(){openOperation('Thread / Helix',[{key:'radius',label:'Helix radius (mm)',type:'number',value:12,step:.1},{key:'pitch',label:'Pitch (mm)',type:'number',value:2,step:.1},{key:'turns',label:'Turns',type:'number',value:8,step:.25},{key:'wire',label:'Thread profile radius (mm)',type:'number',value:.8,step:.05},{key:'mode',label:'Operation',type:'select',value:'new',options:[['new','New helix solid'],['join','Join to selected'],['cut','Cut from selected']]}],async v=>{const before=captureState(),g=makeCoilGeometry(safeNum(v.radius,12),safeNum(v.wire,.8),safeNum(v.pitch,2),safeNum(v.turns,8)),tool=new THREE.Mesh(g,defaultMaterial());tool.position.copy(app.selected?.position||new THREE.Vector3());if(v.mode==='new'){addItem(tool,'solid',{feature:'thread'},`Thread ${app.objectCounter++}`);addFeature(tool,'Helical Thread');}else{if(!app.selected?.isMesh)return setStatus('Select a solid for Join/Cut thread.');const result=await booleanObjects(app.selected,tool,v.mode==='join'?'union':'cut');modelRoot.remove(app.selected);selectObject(result);addFeature(result,'Thread / Helix');}pushHistory('Thread / Helix',before);});}
