// ---------- Guides / measurement ----------
function guidePointFromEvent(e){const hit=hitModel(e);return hit?.point?snapWorld(hit.point):pointerOnSketch(e);}
function handleMeasureClick(p,type){app.drawPoints.push(p.toArray());if((type==='measure'||type==='guide')&&app.drawPoints.length===2){const a=new THREE.Vector3().fromArray(app.drawPoints[0]),b=new THREE.Vector3().fromArray(app.drawPoints[1]),d=a.distanceTo(b);const g=new THREE.BufferGeometry().setFromPoints([a,b]);const l=new THREE.Line(g,lineMaterial(type==='guide'?0xf1c75b:0x7ee4a8));l.userData.helper=true;l.userData.measure=d;guideRoot.add(l);setStatus(`${type==='guide'?'Guide':'Distance'}: ${round(d)} mm`);$('inspectOutput').innerHTML=`Distance: <strong>${round(d)} mm</strong>`;finishSketchTool();}
  if(type==='protractor'&&app.drawPoints.length===3){const a=new THREE.Vector3().fromArray(app.drawPoints[0]),v=new THREE.Vector3().fromArray(app.drawPoints[1]),b=new THREE.Vector3().fromArray(app.drawPoints[2]),va=a.clone().sub(v).normalize(),vb=b.clone().sub(v).normalize(),ang=Math.acos(clamp(va.dot(vb),-1,1))*DEG;const g=new THREE.BufferGeometry().setFromPoints([a,v,b]);const l=new THREE.Line(g,lineMaterial(0xe8a95b));l.userData.helper=true;guideRoot.add(l);setStatus(`Angle: ${round(ang,2)}°`);$('inspectOutput').innerHTML=`Angle: <strong>${round(ang,2)}°</strong>`;finishSketchTool();}}

// ---------- Sketch modify / constraints ----------
function offsetSelectedProfile(){const o=app.selected,meta=rs(o);if(meta?.kind!=='profile')return setStatus('Select a closed sketch profile first.');const before=captureState(),dist=safeNum($('sketchOffsetDistance').value,2),pts=meta.params.points||[];const c=polygonCentroid2D(pts);const out=pts.map(p=>{const dx=p[0]-c[0],dy=p[1]-c[1],m=Math.hypot(dx,dy)||1;return [p[0]+dx/m*dist,p[1]+dy/m*dist]});const n=addProfile(out,meta.params.plane,`${meta.params.shape||'profile'} offset`,{points:out});n.position.copy(o.position);n.rotation.copy(o.rotation);n.scale.copy(o.scale);pushHistory('Offset sketch',before);}
function polygonCentroid2D(pts){let x=0,y=0;pts.forEach(p=>{x+=p[0];y+=p[1]});return [x/pts.length,y/pts.length];}
function constrainSelected(type){const o=app.selected,m=rs(o);if(m?.kind!=='path')return setStatus('Select a sketch line/path for this constraint.');const pts=(m.params.points||[]).map(a=>new THREE.Vector3().fromArray(a));if(pts.length<2)return;const before=captureState();if(type==='horizontal'){const z=pts[0].z;pts[1].z=z;}else if(type==='vertical'){pts[1].x=pts[0].x;pts[1].y=pts[0].y;}else if(type==='fix'){m.locked=!m.locked;}else if(type==='midpoint'&&app.checked.length>=1){const target=app.checked[0].position;const mid=pts[0].clone().add(pts[1]).multiplyScalar(.5),delta=target.clone().sub(mid);pts.forEach(p=>p.add(delta));}else return setStatus(`${capitalize(type)} constraint is recorded; select compatible geometry for a geometric solve.`);m.params.points=pts.map(p=>p.toArray());o.geometry.dispose();o.geometry=new THREE.BufferGeometry().setFromPoints(pts);addFeature(o,`Constraint: ${type}`);pushHistory(`Constraint ${type}`,before);renderSceneList();}
