// ---------- Basic geometry ----------
function makePrimitive(type,params={}){
  let g,p;
  if(type==='box'){p={w:40,d:40,h:30,radius:0,...params};g=p.radius>0?new RoundedBoxGeometry(p.w,p.d,p.h,4,p.radius):new THREE.BoxGeometry(p.w,p.d,p.h);}
  else if(type==='cylinder'){p={r:18,h:35,...params};g=new THREE.CylinderGeometry(p.r,p.r,p.h,64);g.rotateX(Math.PI/2);}
  else if(type==='cone'){p={r:20,h:40,...params};g=new THREE.ConeGeometry(p.r,p.h,64);g.rotateX(Math.PI/2);}
  else if(type==='sphere'){p={r:20,...params};g=new THREE.SphereGeometry(p.r,64,36);}
  else if(type==='torus'){p={r:24,tube:6,...params};g=new THREE.TorusGeometry(p.r,p.tube,24,80);}
  else if(type==='tube'){p={ro:20,ri:14,h:40,...params};g=makeHollowTube(p.ro,p.ri,p.h);}
  else if(type==='coil'){p={r:22,tube:2,pitch:8,turns:5,...params};g=makeCoilGeometry(p.r,p.tube,p.pitch,p.turns);}
  else return null;
  g.computeVertexNormals();const m=new THREE.Mesh(g,defaultMaterial());m.castShadow=m.receiveShadow=true;
  addItem(m,'primitive',{type,...p},`${capitalize(type)} ${app.objectCounter++}`);placeOnGround(m,false);pushHistory(`Create ${type}`);fitObjects([m]);return m;
}
function makeHollowTube(ro,ri,h){const shape=new THREE.Shape();shape.absarc(0,0,ro,0,Math.PI*2,false);const hole=new THREE.Path();hole.absarc(0,0,ri,0,Math.PI*2,true);shape.holes.push(hole);const g=new THREE.ExtrudeGeometry(shape,{depth:h,bevelEnabled:false,curveSegments:64});return g;}
function makeCoilGeometry(r,tube,pitch,turns){const pts=[];const n=Math.max(48,Math.round(turns*64));for(let i=0;i<=n;i++){const a=i/n*Math.PI*2*turns;pts.push(new THREE.Vector3(r*Math.cos(a),r*Math.sin(a),pitch*a/(Math.PI*2)));}const curve=new THREE.CatmullRomCurve3(pts);return new THREE.TubeGeometry(curve,n,tube,12,false);}
function rebuildParametric(obj){const meta=rs(obj);if(!meta)return;if(meta.kind==='primitive'){const repl=makeGeometryOnly(meta.params.type,meta.params);if(repl){obj.geometry.dispose();obj.geometry=repl;obj.geometry.computeVertexNormals();placeOnGround(obj,false);syncInspector();}}else if(meta.kind==='profile'){const pts=profilePointsFromParams(meta.params);if(pts){meta.params.points=pts;const repl=makeProfileGeometry(pts,meta.params.plane||'XY');obj.geometry.dispose();obj.geometry=repl;syncInspector();}}}
function makeGeometryOnly(type,p){if(type==='box'){let g=p.radius>0?new RoundedBoxGeometry(p.w,p.d,p.h,4,p.radius):new THREE.BoxGeometry(p.w,p.d,p.h);return g;}if(type==='cylinder'){const g=new THREE.CylinderGeometry(p.r,p.r,p.h,64);g.rotateX(Math.PI/2);return g;}if(type==='cone'){const g=new THREE.ConeGeometry(p.r,p.h,64);g.rotateX(Math.PI/2);return g;}if(type==='sphere')return new THREE.SphereGeometry(p.r,64,36);if(type==='torus')return new THREE.TorusGeometry(p.r,p.tube,24,80);if(type==='tube')return makeHollowTube(p.ro,p.ri,p.h);if(type==='coil')return makeCoilGeometry(p.r,p.tube,p.pitch,p.turns);return null;}
function profilePointsFromParams(p){const old=Array.isArray(p.points)&&p.points.length?p.points:null;let cu=0,cv=0;if(old){old.forEach(q=>{cu+=safeNum(q[0]);cv+=safeNum(q[1]);});cu/=old.length;cv/=old.length;}if(p.shape==='rectangle')return [[cu-p.w/2,cv-p.h/2],[cu+p.w/2,cv-p.h/2],[cu+p.w/2,cv+p.h/2],[cu-p.w/2,cv+p.h/2]];if(p.shape==='circle'||p.shape==='polygon'){const n=p.shape==='circle'?64:(p.sides||6),out=[];for(let i=0;i<n;i++){const a=i/n*Math.PI*2;out.push([cu+p.r*Math.cos(a),cv+p.r*Math.sin(a)]);}return out;}return p.points||null;}
function makeProfileGeometry(points,plane='XY'){const shape=new THREE.Shape();shape.moveTo(points[0][0],points[0][1]);points.slice(1).forEach(p=>shape.lineTo(p[0],p[1]));shape.closePath();const g=new THREE.ShapeGeometry(shape);mapGeometryPlane(g,plane);return g;}
function mapGeometryPlane(g,plane,depthSign=1){const a=g.attributes.position.array;for(let i=0;i<a.length;i+=3){const u=a[i],v=a[i+1],w=a[i+2]*depthSign;if(plane==='XY'){a[i]=u;a[i+1]=v;a[i+2]=w;}else if(plane==='XZ'){a[i]=u;a[i+1]=w;a[i+2]=v;}else{a[i]=w;a[i+1]=u;a[i+2]=v;}}g.attributes.position.needsUpdate=true;g.computeVertexNormals();return g;}
function addProfile(points,plane,shapeType='custom',params={}){const g=makeProfileGeometry(points,plane);const m=new THREE.Mesh(g,profileMaterial());m.renderOrder=2;addItem(m,'profile',{shape:shapeType,plane,points,...params},`${capitalize(shapeType)} Profile ${app.objectCounter++}`);pushHistory(`Create ${shapeType} profile`);return m;}
function addPath(worldPoints,type='path',params={}){const g=new THREE.BufferGeometry().setFromPoints(worldPoints);const l=new THREE.Line(g,lineMaterial(0x75d0ff));addItem(l,'path',{type,points:worldPoints.map(p=>p.toArray()),...params},`${capitalize(type)} Path ${app.objectCounter++}`);pushHistory(`Create ${type} path`);return l;}
function placeOnGround(obj,record=true){if(!obj)return;const before=record?captureState():null;obj.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(obj);obj.position.z-=b.min.z;obj.updateMatrixWorld(true);if(record)pushHistory('Place on Ground',before);syncInspector(false);}
function centerOrigin(obj=app.selected){if(!obj)return;const before=captureState();const b=new THREE.Box3().setFromObject(obj),c=new THREE.Vector3();b.getCenter(c);obj.position.x-=c.x;obj.position.y-=c.y;pushHistory('Center at Origin',before);syncInspector(false);}
